name: Build & Push to Staging Deploy Repository

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/deploy.yaml"
      - "src/**"
      - "index.html"
      - "package-lock.json"
      - "package.json"
      - "tsconfig.json"

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Stage
        run: npm run stage
      - name: Add CNAME
        run: echo "app.cycas.dev" > dist/CNAME
      - name: Push to Staging Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.STAGING_TOKEN }}
          external_repository: bashar-515/cycas-web-staging
          publish_branch: main
          publish_dir: ./dist
